# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LgmInterlinking
                                 A QGIS plugin
 This plugin implements and evaluates the proposed LinkGeoML models for POI classification-based interlinking.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-08
        copyright            : (C) 2020 by Ilias Varkas / Eratosthenis SA
        email                : ivarkas@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LgmInterlinking class from file LgmInterlinking.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .poi_interlinking import LgmInterlinking
    return LgmInterlinking(iface)
